# Generated by Django 2.1.1 on 2018-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppendInfos',
            fields=[
                ('UserId', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('UserId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('DeliveryState', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ItemId', models.BigIntegerField()),
                ('UserId', models.BigIntegerField()),
                ('Comment', models.TextField(max_length=65535)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('SubCommentId', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('Follower', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Following', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('UserId', models.BigIntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=65535)),
                ('ShortCut', models.CharField(max_length=50)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('Place', models.CharField(max_length=50)),
                ('Classification', models.CharField(max_length=50)),
                ('AppendInfoId', models.CharField(max_length=50)),
                ('VisitNum', models.IntegerField(default=0)),
                ('XinJiu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('BuyerId', models.BigIntegerField()),
                ('SellerId', models.BigIntegerField()),
                ('ItemId', models.BigIntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('DeliveryState', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('RewardId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('UserId', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=65535)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('UserId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Credit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Nickname', models.CharField(max_length=50)),
                ('Icon', models.ImageField(upload_to='')),
                ('Photo', models.ImageField(upload_to='')),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
